"use strict";var s=Object.defineProperty;var d=Object.getOwnPropertyDescriptor;var f=Object.getOwnPropertyNames;var A=Object.prototype.hasOwnProperty;var k=(t,e)=>{for(var o in e)s(t,o,{get:e[o],enumerable:!0})},T=(t,e,o,p)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of f(e))!A.call(t,r)&&r!==o&&s(t,r,{get:()=>e[r],enumerable:!(p=d(e,r))||p.enumerable});return t};var m=t=>T(s({},"__esModule",{value:!0}),t);var P={};k(P,{default:()=>D});module.exports=m(P);var i=require("@raycast/api");var a=require("@raycast/api");var n={APP_NAME:"Drafts",APP_BUNDLE_ID:"com.agiletortoise.Drafts-OSX",APP_DOWNLOAD_LINK:"https://getdrafts.com"};var l=[{name:"CREATE_DRAFT",buttonDescription:"Create Draft",mdDescription:"create a draft",link:"drafts://x-callback-url/create?text={Content}"},{name:"QUICK_SEARCH",buttonDescription:"Quick Search",mdDescription:"open the quicksearch in Drafts",link:"drafts://x-callback-url/quickSearch?query={Quicksearch}"},{name:"DRAFTS_LIST_SEARCH",buttonDescription:"Search Drafts List",mdDescription:"search in the drafts list",link:"drafts://x-callback-url/search?query={Search Drafts}"},{name:"ACTION_LIST_SEARCH",buttonDescription:"Search Actions List",mdDescription:"search in the Action list",link:"drafts://x-callback-url/actionSearch?query={Search Actions}"},{name:"CAPTURE",buttonDescription:"Capture Text",mdDescription:"capture text with Drafts capture window",link:"drafts://x-callback-url/capture?text={Text}"},{name:"DICTATE",buttonDescription:"Dictate to Drafts",mdDescription:"open the dictation window",link:"drafts://x-callback-url/dictate?"}];async function h(){return(await(0,a.getApplications)()).some(({bundleId:e})=>e===n.APP_BUNDLE_ID)}async function u(){if(!await h()){let t={style:a.Toast.Style.Failure,title:n.APP_NAME+" is not installed.",message:"Install it from: "+n.APP_DOWNLOAD_LINK,primaryAction:{title:"Open "+n.APP_DOWNLOAD_LINK,onAction:e=>{(0,a.open)(n.APP_DOWNLOAD_LINK),e.hide()}}};return await(0,a.showToast)(t),!1}return!0}var c=require("react/jsx-runtime"),_=`# Drafts Quicklink Helper

This is a helper action to easily create Raycast Quicklinks for Drafts.
To add a Quicklink simply run one of the included actions (press \`\u2318 + K\` to expand the menu). 

In the displayed menu you can give the new Quicklink a name of your choice and press \`\u2318 + \u21B5\`.

You can add Quicklinks to do the following things:
${l.map(t=>"- "+t.mdDescription).join(`
`)}

To use your created Quicklinks just search for the names you selected and e.g. type the search string / content for a new draft into the search field.
`;function D(){return u(),(0,c.jsx)(i.Detail,{markdown:_,actions:(0,c.jsx)(i.ActionPanel,{children:l.map((t,e)=>(0,c.jsx)(i.Action.CreateQuicklink,{quicklink:{link:t.link},icon:i.Icon.Plus,title:"Create Quicklink to "+t.buttonDescription},e))})})}
